# Generated by Django 6.0.4 on 2026-06-08 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['-fecha_apertura']},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(default='', help_text='Documento Nacional de Identidad único', max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No especifica')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ingreso_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nivel_educativo',
            field=models.CharField(choices=[('primario', 'Primario'), ('secundario', 'Secundario'), ('terciario', 'Terciario/Tecnicatura'), ('universitario', 'Universitario'), ('posgrado', 'Posgrado/Master')], default='secundario', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ocupación/Profesión'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='score_crediticio_inicial',
            field=models.IntegerField(default=500, help_text='Score externo de riesgo al registrarse'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('completada', 'Completada'), ('pendiente', 'Pendiente'), ('fallida', 'Fallida'), ('revertida', 'Revertida')], db_index=True, default='completada', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('deposito', 'Depósito'), ('retiro', 'Retiro'), ('pago_tarjeta', 'Pago con Tarjeta'), ('pago_prestamo', 'Pago de Préstamo')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='AlertaFraude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_riesgo', models.FloatField()),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('accion_tomada', models.CharField(choices=[('ninguna', 'Ninguna / En revisión'), ('bloqueo_cuenta', 'Bloqueo de Cuenta'), ('notificacion_cliente', 'Notificación Enviada'), ('transaccion_rechazada', 'Transacción Rechazada')], default='ninguna', max_length=50)),
                ('resuelta', models.BooleanField(default=False)),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerta', to='infrastructure.transaccion')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos_fallidos_login', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('doble_factor_activo', models.BooleanField(default=False)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_seguridad', to='infrastructure.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_interes_anual', models.FloatField()),
                ('plazo_meses', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('vencido', 'Vencida/Mora')], default='activo', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='infrastructure.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='infrastructure.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarjeta', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=20)),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('cvv', models.CharField(max_length=4)),
                ('fecha_expiracion', models.DateField()),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('bloqueada', 'Bloqueada'), ('vencida', 'Vencida')], default='activa', max_length=20)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='infrastructure.cuenta')),
            ],
        ),
    ]
