# Generated by Django 6.0.4 on 2026-06-08 12:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_alter_cliente_options_alter_cuenta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertafraude',
            options={'ordering': ['-fecha_alerta'], 'verbose_name': 'Alerta de fraude', 'verbose_name_plural': 'Alertas de fraude'},
        ),
        migrations.AlterModelOptions(
            name='configuracionseguridad',
            options={'verbose_name': 'Configuración de seguridad', 'verbose_name_plural': 'Configuraciones de seguridad'},
        ),
        migrations.AlterModelOptions(
            name='cuotaprestamo',
            options={'ordering': ['prestamo', 'numero_cuota'], 'verbose_name': 'Cuota de préstamo', 'verbose_name_plural': 'Cuotas de préstamo'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'ordering': ['-fecha_expiracion'], 'verbose_name': 'Tarjeta', 'verbose_name_plural': 'Tarjetas'},
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='cvv',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(help_text='Documento Nacional de Identidad (7 u 8 dígitos)', max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'El DNI debe tener 7 u 8 dígitos numéricos.')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ingreso_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ingreso mensual estimado'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas', to='infrastructure.cuenta'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'El número de tarjeta debe tener exactamente 16 dígitos.')]),
        ),
    ]
