# Generated by Django 6.0.4 on 2026-06-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_alter_alertafraude_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='numero_cuenta',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
