# Generated by Django 6.0.4 on 2026-06-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_cuenta_numero_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='alias',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cvu',
            field=models.CharField(blank=True, max_length=22, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cuotaprestamo',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuotaprestamo',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='sistema_amortizacion',
            field=models.CharField(choices=[('frances', 'Francés'), ('aleman', 'Alemán')], default='frances', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='moneda',
            field=models.CharField(default='ARS', max_length=3),
        ),
    ]
