# Generated by Django 6.0.4 on 2026-07-07 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_cuenta_alias_cuenta_cvu_cuotaprestamo_fecha_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlazoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo_dias', models.IntegerField()),
                ('tasa_interes_anual', models.FloatField()),
                ('fecha_constitucion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('monto_al_vencimiento', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plazos_fijos', to='infrastructure.cliente')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plazos_fijos', to='infrastructure.cuenta')),
            ],
            options={
                'verbose_name': 'Plazo fijo',
                'verbose_name_plural': 'Plazos fijos',
                'ordering': ['-fecha_constitucion'],
            },
        ),
    ]
