# Generated by Django 6.0.4 on 2026-07-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_plazofijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='debito_automatico',
            field=models.BooleanField(default=False),
        ),
    ]
